name: gligen
channels:
  - pytorch
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
#show_channel_urls: true
#default_channels:
#  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
#  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
#  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
#custom_channels:
#  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
#  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
#  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
#  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
#  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
#  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
#  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud

dependencies:
  - python=3.10.8
  - pip=22.2.2
  - cudatoolkit=11.6
  - pytorch=1.13.0
  - torchvision=0.14.0
  - numpy=1.23.1
  - xformers
  - pip:
    - omegaconf==2.1.1
    - albumentations==0.4.3
    - opencv-python
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - git+https://github.com/openai/CLIP.git
    - protobuf~=3.20.1 torchmetrics==0.6.0
    - transformers==4.19.2
    - kornia==0.5.8
#    - && pip uninstall -y torchtext