diffusion:
  target: ldm.models.diffusion.ldm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    timesteps: 1000
#    first_stage_key: "jpg"
#    cond_stage_key: "txt"

model:
  target: ldm.modules.diffusionmodules.openaimodel.UNetModel
  params:
    image_size: 64 # unused in the unet, but will be used when create xT
    in_channels: 4
    out_channels: 4
    model_channels: 320
    attention_resolutions: [ 4, 2, 1 ]
    num_res_blocks: 2
    channel_mult: [ 1, 2, 4, 4 ]
    num_heads: 8
    transformer_depth: 1
    context_dim: 1024  #1024 in SDv2 ; 768 in SDv1
    fuser_type: gatedSA  #  gatedCA or gatedSA. We have ablate this, self-attention is better than cross-attention, thus please set this as gatedSA usually
    use_checkpoint: True
    use_linear_in_transformer: True  # True in SD2; False in SD1


    grounding_downsampler:
        target: ldm.modules.diffusionmodules.sem_depth_grounding_downsampler.GroundingDownsampler
        params:
          in_dim: 152  # seg
          resize_input: 256
          out_dim: 8


    grounding_tokenizer:
        target: ldm.modules.diffusionmodules.sem_depth_grounding_net.PositionNet
        params:
          in_dim: 152
          resize_input: 256
          out_dim: 1024  #1024 in SDv2 ; 768 in SDv1


autoencoder:
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    scale_factor: 0.18215
    embed_dim: 4
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0


text_encoder:
  target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder


train_dataset_names:
  Sem_Depth:
    prob_use_caption: 1
    image_size: 512
    random_flip: True


grounding_tokenizer_input:
  target: grounding_input.sem_depth_grounding_tokinzer_input.GroundingNetInput


grounding_downsampler_input:
  target: grounding_input.sem_depth_grounding_downsampler_input.GroundingDSInput


